server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - optional:file:ET-api-gateway/.env[.properties]

  application:
    name: ET-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://ET-user
            predicates:
             - Path=/api/users/**, /api/friends/**, /api/auth/**

          - id: CORE-SERVICE
            uri: lb://ET-core
            predicates:
              - Path=/api/stocks/**, /api/charts/**, /api/trades/**

          - id: ARCADE-SERVICE
            uri: lb://ET-arcade
            predicates:
              - Path=/api/pets/**, /api/quizs/**, /api/eggs/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}